import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f1f",
        "on-primary-container": "#00626e",
        "on-primary": "#00363d",
        "tertiary-fixed-dim": "#c7c5ce",
        "on-background": "#e5e2e1",
        background: "#131313",
        primary: "#c3f5ff",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed": "#1b1b21",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#3a3939",
        "on-primary-fixed": "#001f24",
        "primary-fixed-dim": "#00daf3",
        "surface-tint": "#00daf3",
        "on-error": "#690005",
        error: "#ffb4ab",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        "outline-variant": "#3b494c",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-highest": "#353534",
        "on-tertiary-container": "#58585f",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary-fixed": "#e3e1ea",
        "on-tertiary-fixed-variant": "#46464d",
        "on-surface-variant": "#bac9cc",
        "on-tertiary": "#303037",
        "surface-dim": "#131313",
        surface: "#131313",
        "on-secondary-container": "#b7b5b4",
        "on-surface": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        tertiary: "#eeebf4",
        "secondary-fixed": "#e5e2e1",
        secondary: "#c8c6c5",
        "secondary-container": "#474746",
        outline: "#849396",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#d1cfd8",
        "primary-fixed": "#9cf0ff",
        "inverse-primary": "#006875",
        "error-container": "#93000a",
        "surface-variant": "#353534",
        "on-primary-fixed-variant": "#004f58",
        "primary-container": "#00e5ff",
        "on-secondary": "#313030",
        "surface-container-high": "#2a2a2a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "4rem",
        xs: "0.5rem",
        md: "1.5rem",
        unit: "4px",
        "margin-mobile": "20px",
        gutter: "24px",
        sm: "1rem",
        "margin-desktop": "64px",
        lg: "2.5rem",
      },
      fontFamily: {
        "headline-md": ["var(--font-geist)", "sans-serif"],
        "display-lg-mobile": ["var(--font-geist)", "sans-serif"],
        "body-md": ["var(--font-geist)", "sans-serif"],
        "label-md": ["var(--font-jetbrains-mono)", "monospace"],
        "label-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "display-lg": ["var(--font-geist)", "sans-serif"],
        "headline-sm": ["var(--font-geist)", "sans-serif"],
        "body-lg": ["var(--font-geist)", "sans-serif"],
      },
      fontSize: {
        "headline-md": [
          "30px",
          { lineHeight: "1.3", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
