import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "surface-container": "#f1f3ee",
        "on-primary-container": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c7c5ce",
        "on-background": "#111827",
        background: "#fcfcf8",
        primary: "#db4d08",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed": "#1b1b21",
        "surface-container-lowest": "#e7ebe3",
        "surface-bright": "#ffffff",
        "on-primary-fixed": "#2b160b",
        "primary-fixed-dim": "#d64a08",
        "surface-tint": "#d64a08",
        "on-error": "#690005",
        error: "#ffb4ab",
        "surface-container-low": "#f7f8f4",
        "on-secondary-fixed-variant": "#474746",
        "outline-variant": "#d8ddd2",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-highest": "#e9ede4",
        "on-tertiary-container": "#58585f",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary-fixed": "#e3e1ea",
        "on-tertiary-fixed-variant": "#46464d",
        "on-surface-variant": "#596273",
        "on-tertiary": "#303037",
        "surface-dim": "#f5f6f1",
        surface: "#ffffff",
        "on-secondary-container": "#b7b5b4",
        "on-surface": "#111827",
        "inverse-surface": "#e5e2e1",
        tertiary: "#eeebf4",
        "secondary-fixed": "#e5e2e1",
        secondary: "#c8c6c5",
        "secondary-container": "#474746",
        outline: "#849396",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#d1cfd8",
        "primary-fixed": "#ffb17f",
        "inverse-primary": "#ffb17f",
        "error-container": "#93000a",
        "surface-variant": "#e9ede4",
        "on-primary-fixed-variant": "#8d3100",
        "primary-container": "#ee5a11",
        "on-secondary": "#313030",
        "surface-container-high": "#edf0e9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "4rem",
        xs: "0.5rem",
        md: "1.5rem",
        unit: "4px",
        "margin-mobile": "20px",
        gutter: "24px",
        sm: "1rem",
        "margin-desktop": "64px",
        lg: "2.5rem",
      },
      fontFamily: {
        "headline-md": ["var(--font-geist)", "sans-serif"],
        "display-lg-mobile": ["var(--font-geist)", "sans-serif"],
        "body-md": ["var(--font-geist)", "sans-serif"],
        "label-md": ["var(--font-jetbrains-mono)", "monospace"],
        "label-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "display-lg": ["var(--font-geist)", "sans-serif"],
        "headline-sm": ["var(--font-geist)", "sans-serif"],
        "body-lg": ["var(--font-geist)", "sans-serif"],
      },
      fontSize: {
        "headline-md": [
          "30px",
          { lineHeight: "1.3", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
